name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_ACTION: GITHUB_ACTION
        uses: Ilshidur/action-discord@master
        with: 
          args: '{{GITHUB_ACTOR}} pushed the commit {{GITHUB_SHA}} to {{GITHUB_REPOSITORY}}'
